using System.Text;
using Microsoft.CodeAnalysis;

namespace AraonMC.SourceGenerators;

/// <summary>
///     Emits an internal <c>Secrets</c> class with <c>MsOAuthClientId</c> baked in from the
///     <c>MS_CLIENT_ID</c> MSBuild property at compile time. Gated by
///     <c>&lt;AraonMCGenerateSecrets&gt;true&lt;/AraonMCGenerateSecrets&gt;</c> so only the consuming
///     app receives it; empty when the property is unset.
/// </summary>
[Generator]
public sealed class SecretsSourceGenerator : IIncrementalGenerator
{
    private const string GenerateSecretsProperty = "build_property.AraonMCGenerateSecrets";
    private const string MsClientIdProperty = "build_property.PCL_MS_CLIENT_ID";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var secrets = context.AnalyzerConfigOptionsProvider.Select((opts, _) =>
        {
            var enabled = opts.GlobalOptions.TryGetValue(GenerateSecretsProperty, out var gateRaw)
                          && bool.TryParse(gateRaw, out var gate) && gate;
            if (!enabled) return (Enabled: false, ClientId: string.Empty);

            opts.GlobalOptions.TryGetValue(MsClientIdProperty, out var clientId);
            return (Enabled: true, ClientId: clientId ?? string.Empty);
        });

        context.RegisterSourceOutput(secrets, (spc, data) =>
        {
            if (!data.Enabled) return;
            spc.AddSource("Secrets.Generated.g.cs", Emit(data.ClientId));
        });
    }

    private static string Emit(string clientId)
    {
        return $@"// <auto-generated/>
#nullable enable
namespace AraonMC;

/// <summary>
///     Compile-time secrets. Values are read from MSBuild properties (e.g.
///     <c>MS_CLIENT_ID</c>, sourced from the build environment) by the source generator at build
///     time, then baked in as constants.
/// </summary>
internal static class Secrets
{{
    /// <summary>
    ///     The Microsoft OAuth public-client id. Set the <c>MS_CLIENT_ID</c> environment variable
    ///     before building; empty when unset (the account service reports a configuration error).
    /// </summary>
    public const string MsOAuthClientId = {EmitStringLiteral(clientId)};
}}
";
    }

    /// <summary>
    ///     Produces a C# string literal, escaping backslash and double-quote. Client ids are opaque
    ///     ASCII tokens, so no need to handle exotic whitespace/control characters.
    /// </summary>
    private static string EmitStringLiteral(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var c in value)
        {
            if (c == '\\' || c == '"') sb.Append('\\');
            sb.Append(c);
        }
        sb.Append('"');
        return sb.ToString();
    }
}
