using AraonMC.Core.Domain.Entities;

namespace AraonMC.Core.Config;

/// <summary>
/// A typed accessor for an <see cref="ConfigScope.Instance"/>-scoped key. Indexing by a
/// <see cref="MinecraftInstance"/> reads/writes the value stored under that instance's
/// absolute path. Generated by the source generator as <c>Config.Section.Key[instance]</c>.
/// </summary>
public sealed class InstanceKey<T>
{
    private readonly IConfigStore _store;
    private readonly ConfigScope _scope;
    private readonly string _path;
    private readonly T? _default;

    public InstanceKey(IConfigStore store, ConfigScope scope, string path, T? @default)
    {
        _store = store;
        _scope = scope;
        _path = path;
        _default = @default;
    }

    /// <summary>Read/write this key for <paramref name="instance"/> (keyed by its absolute path).</summary>
    public T? this[MinecraftInstance instance]
    {
        get => _store.Get(_scope, _path, _default, instance.Path);
        set => _store.Set(_scope, _path, value, instance.Path);
    }
}
